view:
  site:
    websiteName: 技术博客园
    contactMeWxQrCode: https://cdn.tobebetterjavaer.com/paicoding/paicoding-qrcode.png
    pageSize: 20
    cdnImgStyle:
    websiteRecord: 听风吟
    host: https://paicoding.com
    welcomeInfo: 欢迎来到技术博客园，戳 <a href="/article/detail/155">技术派社区上线！</a> 了解我们
    contactMeStarQrCode: https://cdn.tobebetterjavaer.com/tobebetterjavaer/images/qiye-weixin.png
    oss: https://cdn.tobebetterjavaer.com/paicoding/static

knife4j:
  production: true # 开启屏蔽文档资源