view:
  site:
    websiteName: 技术博客园
    contactMeWxQrCode: https://technology-blogs.oss-cn-shanghai.aliyuncs.com/blogs/wxImages/wxLoginImage.jpg
    pageSize: 20
    websiteRecord: 听风吟
    host: https://www.baidu.com/
    welcomeInfo: 欢迎来到技术博客园，这里是一个技术分享的平台。
    contactMeStarQrCode: https://cdn.tobebetterjavaer.com/tobebetterjavaer/images/qiye-weixin.png
    oss:

knife4j:
  production: true # 开启屏蔽文档资源